# Generated by Django 4.2.7 on 2023-11-29 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                ("modelid", models.AutoField(primary_key=True, serialize=False)),
                ("trainingdate", models.DateField(default=datetime.datetime.today)),
                (
                    "training_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "testing_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("model_weights", models.FileField(null=True, upload_to="models/")),
                ("is_deployed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-training_accuracy", "-testing_accuracy"),
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation_name", models.CharField(max_length=100)),
                ("translation_date", models.DateField(default=datetime.datetime.today)),
                ("translation_file", models.FileField(null=True, upload_to="output/")),
                (
                    "translation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
