# Generated by Django 4.2.7 on 2023-11-22 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                ("modelid", models.AutoField(primary_key=True, serialize=False)),
                ("trainingdate", models.DateField(default=datetime.datetime.today)),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
