# Generated by Django 4.2.7 on 2023-12-06 08:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.validations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation_input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_date", models.DateField(default=datetime.datetime.today)),
                (
                    "input_file",
                    models.FileField(
                        null=True,
                        upload_to="input/",
                        validators=[
                            website.validations.validate_mp4,
                            website.validations.validate_file_size,
                        ],
                    ),
                ),
                (
                    "input_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation_output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output_file", models.FileField(null=True, upload_to="output/")),
                (
                    "output_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output_sourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.translation_input",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training_input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tr_input_file",
                    models.FileField(
                        default={},
                        null=True,
                        upload_to="input/",
                        validators=[website.validations.validate_json],
                    ),
                ),
                (
                    "tr_input_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("training_date", models.DateField(default=datetime.datetime.today)),
                (
                    "training_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "testing_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("model_weights", models.FileField(null=True, upload_to="models/")),
                ("is_deployed", models.BooleanField(default=False)),
                (
                    "tr_input_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.training_input",
                    ),
                ),
            ],
            options={
                "ordering": ("-training_accuracy", "-testing_accuracy"),
            },
        ),
    ]
