# Generated by Django 5.0 on 2023-12-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='is_deployed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='model_weights',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testing_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='tr_input_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.training_input'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
