# Generated by Django 4.2.7 on 2023-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ("-accuracy",)},
        ),
        migrations.AddField(
            model_name="training",
            name="isdeployed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="training",
            name="modelweights",
            field=models.FileField(null=True, upload_to="media/models/"),
        ),
    ]
