# Generated by Django 4.2.7 on 2023-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translation",
            old_name="translation_file",
            new_name="translation_output",
        ),
        migrations.AddField(
            model_name="translation",
            name="translation_input",
            field=models.FileField(null=True, upload_to="input/"),
        ),
    ]
