# Generated by Django 4.2.7 on 2023-12-03 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "website",
            "0002_rename_translation_file_translation_translation_output_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation_input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_date", models.DateField(default=datetime.datetime.today)),
                ("input_file", models.FileField(null=True, upload_to="input/")),
                (
                    "input_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation_output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output_file", models.FileField(null=True, upload_to="output/")),
                (
                    "output_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output_sourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.translation_input",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
    ]
