# Generated by Django 5.0 on 2023-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_training_is_deployed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='testing_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
