# Generated by Django 4.2.7 on 2023-12-05 15:28

from django.db import migrations, models
import website.validations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_translation_input_translation_output_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation_input",
            name="input_file",
            field=models.FileField(
                null=True,
                upload_to="input/",
                validators=[
                    website.validations.validate_file_format,
                    website.validations.validate_file_size,
                ],
            ),
        ),
    ]
